#!/usr/bin/env bash
set -e

BUILD_TYPE="Debug"
if [[ "$1" == "-r" ]]; then
    BUILD_TYPE="Release"
fi

cmake -B build -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -Wno-dev
cmake --build build --parallel
./build/renderer
